name = "pokecardex"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "pokecardex-db"
database_id = "placeholder-create-with-wrangler-d1-create"
migrations_dir = "drizzle"
