import { eq } from 'drizzle-orm'
import { createDb } from './index.ts'
import { arbitrageAlerts, cards, priceStats, prices, sets } from './schema.ts'

const db = createDb()

// 3 recent JP Pokemon TCG sets with real data
const seedSets = [
  {
    id: 'sv8',
    nameJa: '超電ブレイカー',
    nameEn: 'Super Electric Breaker',
    codeJa: 'SV8',
    codeEn: null,
    seriesJa: 'スカーレット＆バイオレット',
    seriesEn: 'Scarlet & Violet',
    totalCards: 91,
    releaseDateJa: '2025-01-24',
    releaseDateEn: null,
    imageUrl: null,
  },
  {
    id: 'sv7a',
    nameJa: 'パラダイムトリガー',
    nameEn: 'Paradise Dragona',
    codeJa: 'SV7a',
    codeEn: null,
    seriesJa: 'スカーレット＆バイオレット',
    seriesEn: 'Scarlet & Violet',
    totalCards: 75,
    releaseDateJa: '2024-11-08',
    releaseDateEn: null,
    imageUrl: null,
  },
  {
    id: 'sv7',
    nameJa: 'ステラミラクル',
    nameEn: 'Stellar Miracle',
    codeJa: 'SV7',
    codeEn: null,
    seriesJa: 'スカーレット＆バイオレット',
    seriesEn: 'Scarlet & Violet',
    totalCards: 102,
    releaseDateJa: '2024-07-19',
    releaseDateEn: null,
    imageUrl: null,
  },
]

// Sample cards for each set (representative selection)
const seedCards = [
  // SV8 - 超電ブレイカー
  {
    id: 'sv8-001',
    setId: 'sv8',
    numberInSet: '001/091',
    nameJa: 'タマタマ',
    nameEn: 'Exeggcute',
    rarity: 'C',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 50,
    artist: 'Misa Tsutsui',
  },
  {
    id: 'sv8-007',
    setId: 'sv8',
    numberInSet: '007/091',
    nameJa: 'マスカーニャex',
    nameEn: 'Meowscarada ex',
    rarity: 'RR',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 310,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv8-015',
    setId: 'sv8',
    numberInSet: '015/091',
    nameJa: 'ブーバー',
    nameEn: 'Magmar',
    rarity: 'C',
    typeJa: '炎',
    typeEn: 'Fire',
    hp: 80,
    artist: 'Sanosuke Sakuma',
  },
  {
    id: 'sv8-023',
    setId: 'sv8',
    numberInSet: '023/091',
    nameJa: 'ミライドンex',
    nameEn: 'Miraidon ex',
    rarity: 'RR',
    typeJa: '雷',
    typeEn: 'Lightning',
    hp: 220,
    artist: '5ban Graphics',
  },
  {
    id: 'sv8-030',
    setId: 'sv8',
    numberInSet: '030/091',
    nameJa: 'テツノカシラex',
    nameEn: 'Iron Crown ex',
    rarity: 'RR',
    typeJa: '超',
    typeEn: 'Psychic',
    hp: 220,
    artist: 'PLANETA Igarashi',
  },
  {
    id: 'sv8-040',
    setId: 'sv8',
    numberInSet: '040/091',
    nameJa: 'ガブリアスex',
    nameEn: 'Garchomp ex',
    rarity: 'RR',
    typeJa: '闘',
    typeEn: 'Fighting',
    hp: 330,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv8-050',
    setId: 'sv8',
    numberInSet: '050/091',
    nameJa: 'サザンドラex',
    nameEn: 'Hydreigon ex',
    rarity: 'RR',
    typeJa: '悪',
    typeEn: 'Darkness',
    hp: 320,
    artist: '5ban Graphics',
  },
  {
    id: 'sv8-060',
    setId: 'sv8',
    numberInSet: '060/091',
    nameJa: 'ジュラルドンex',
    nameEn: 'Duraludon ex',
    rarity: 'RR',
    typeJa: '鋼',
    typeEn: 'Metal',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv8-070',
    setId: 'sv8',
    numberInSet: '070/091',
    nameJa: 'カビゴン',
    nameEn: 'Snorlax',
    rarity: 'U',
    typeJa: '無',
    typeEn: 'Colorless',
    hp: 150,
    artist: 'Kouki Saitou',
  },
  {
    id: 'sv8-080',
    setId: 'sv8',
    numberInSet: '080/091',
    nameJa: 'ボスの指令',
    nameEn: "Boss's Orders",
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: 'GOSSAN',
  },

  // SV7a - パラダイムトリガー
  {
    id: 'sv7a-001',
    setId: 'sv7a',
    numberInSet: '001/075',
    nameJa: 'キャタピー',
    nameEn: 'Caterpie',
    rarity: 'C',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 50,
    artist: 'Saya Tsuruta',
  },
  {
    id: 'sv7a-010',
    setId: 'sv7a',
    numberInSet: '010/075',
    nameJa: 'ウルガモスex',
    nameEn: 'Volcarona ex',
    rarity: 'RR',
    typeJa: '炎',
    typeEn: 'Fire',
    hp: 270,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7a-020',
    setId: 'sv7a',
    numberInSet: '020/075',
    nameJa: 'パルキアex',
    nameEn: 'Palkia ex',
    rarity: 'RR',
    typeJa: '水',
    typeEn: 'Water',
    hp: 280,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv7a-030',
    setId: 'sv7a',
    numberInSet: '030/075',
    nameJa: 'ディアルガex',
    nameEn: 'Dialga ex',
    rarity: 'RR',
    typeJa: '鋼',
    typeEn: 'Metal',
    hp: 280,
    artist: 'PLANETA Igarashi',
  },
  {
    id: 'sv7a-040',
    setId: 'sv7a',
    numberInSet: '040/075',
    nameJa: 'アルセウスex',
    nameEn: 'Arceus ex',
    rarity: 'RR',
    typeJa: '無',
    typeEn: 'Colorless',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7a-050',
    setId: 'sv7a',
    numberInSet: '050/075',
    nameJa: 'ギラティナex',
    nameEn: 'Giratina ex',
    rarity: 'RR',
    typeJa: '超',
    typeEn: 'Psychic',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7a-055',
    setId: 'sv7a',
    numberInSet: '055/075',
    nameJa: 'シロナの覇気',
    nameEn: "Cynthia's Ambition",
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: 'Yusuke Kozaki',
  },
  {
    id: 'sv7a-060',
    setId: 'sv7a',
    numberInSet: '060/075',
    nameJa: 'ダブルターボエネルギー',
    nameEn: 'Double Turbo Energy',
    rarity: 'U',
    typeJa: 'エネルギー',
    typeEn: 'Energy',
    hp: null,
    artist: null,
  },

  // SV7 - ステラミラクル
  {
    id: 'sv7-001',
    setId: 'sv7',
    numberInSet: '001/102',
    nameJa: 'フシギダネ',
    nameEn: 'Bulbasaur',
    rarity: 'C',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 70,
    artist: 'Narumi Sato',
  },
  {
    id: 'sv7-010',
    setId: 'sv7',
    numberInSet: '010/102',
    nameJa: 'リザードンex',
    nameEn: 'Charizard ex',
    rarity: 'RR',
    typeJa: '炎',
    typeEn: 'Fire',
    hp: 330,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv7-020',
    setId: 'sv7',
    numberInSet: '020/102',
    nameJa: 'カメックスex',
    nameEn: 'Blastoise ex',
    rarity: 'RR',
    typeJa: '水',
    typeEn: 'Water',
    hp: 330,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-030',
    setId: 'sv7',
    numberInSet: '030/102',
    nameJa: 'ピカチュウex',
    nameEn: 'Pikachu ex',
    rarity: 'RR',
    typeJa: '雷',
    typeEn: 'Lightning',
    hp: 200,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv7-040',
    setId: 'sv7',
    numberInSet: '040/102',
    nameJa: 'ミュウツーex',
    nameEn: 'Mewtwo ex',
    rarity: 'RR',
    typeJa: '超',
    typeEn: 'Psychic',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-050',
    setId: 'sv7',
    numberInSet: '050/102',
    nameJa: 'ルカリオex',
    nameEn: 'Lucario ex',
    rarity: 'RR',
    typeJa: '闘',
    typeEn: 'Fighting',
    hp: 270,
    artist: 'PLANETA Igarashi',
  },
  {
    id: 'sv7-060',
    setId: 'sv7',
    numberInSet: '060/102',
    nameJa: 'ゲンガーex',
    nameEn: 'Gengar ex',
    rarity: 'RR',
    typeJa: '悪',
    typeEn: 'Darkness',
    hp: 270,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-070',
    setId: 'sv7',
    numberInSet: '070/102',
    nameJa: 'テラパゴスex',
    nameEn: 'Terapagos ex',
    rarity: 'RR',
    typeJa: '無',
    typeEn: 'Colorless',
    hp: 230,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-080',
    setId: 'sv7',
    numberInSet: '080/102',
    nameJa: 'ナンジャモ',
    nameEn: 'Iono',
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: 'take',
  },
  {
    id: 'sv7-090',
    setId: 'sv7',
    numberInSet: '090/102',
    nameJa: 'ネストボール',
    nameEn: 'Nest Ball',
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: null,
  },
]

async function seed() {
  console.log('Seeding database...')

  for (const set of seedSets) {
    const existing = await db.select().from(sets).where(eq(sets.id, set.id))
    if (existing.length === 0) {
      await db.insert(sets).values(set)
      console.log(`  + Set: ${set.nameJa} (${set.codeJa})`)
    } else {
      console.log(`  = Set already exists: ${set.nameJa}`)
    }
  }

  for (const card of seedCards) {
    const existing = await db.select().from(cards).where(eq(cards.id, card.id))
    if (existing.length === 0) {
      await db.insert(cards).values(card)
      console.log(`  + Card: ${card.nameJa} / ${card.nameEn}`)
    } else {
      console.log(`  = Card already exists: ${card.nameJa}`)
    }
  }

  // Seed price snapshots for high-value cards
  const now = new Date()
  const seedPrices = [
    // Charizard ex (sv7-010) — high demand, big JP/EN gap
    {
      cardId: 'sv7-010',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 280000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7-010',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 300000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 7),
    },
    {
      cardId: 'sv7-010',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 320000,
      currency: 'JPY',
      condition: 'mint',
      scrapedAt: daysAgo(now, 14),
    },
    {
      cardId: 'sv7-010',
      marketplace: 'yahoo_auctions',
      region: 'jp',
      priceCents: 260000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 1),
    },
    {
      cardId: 'sv7-010',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 3500,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7-010',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 3800,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 7),
    },
    {
      cardId: 'sv7-010',
      marketplace: 'ebay',
      region: 'en',
      priceCents: 4200,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 2),
    },

    // Pikachu ex (sv7-030) — iconic, always popular
    {
      cardId: 'sv7-030',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 150000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7-030',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 160000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 5),
    },
    {
      cardId: 'sv7-030',
      marketplace: 'yahoo_auctions',
      region: 'jp',
      priceCents: 140000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 1),
    },
    {
      cardId: 'sv7-030',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 1800,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7-030',
      marketplace: 'ebay',
      region: 'en',
      priceCents: 2200,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 3),
    },

    // Mewtwo ex (sv7-040) — strong arbitrage opportunity
    {
      cardId: 'sv7-040',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 80000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7-040',
      marketplace: 'yahoo_auctions',
      region: 'jp',
      priceCents: 75000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 2),
    },
    {
      cardId: 'sv7-040',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 1200,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7-040',
      marketplace: 'ebay',
      region: 'en',
      priceCents: 1500,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 1),
    },

    // Miraidon ex (sv8-023) — new set hype
    {
      cardId: 'sv8-023',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 180000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv8-023',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 200000,
      currency: 'JPY',
      condition: 'mint',
      scrapedAt: daysAgo(now, 3),
    },
    {
      cardId: 'sv8-023',
      marketplace: 'yahoo_auctions',
      region: 'jp',
      priceCents: 170000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 1),
    },
    {
      cardId: 'sv8-023',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 2500,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },

    // Garchomp ex (sv8-040) — moderate value
    {
      cardId: 'sv8-040',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 50000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv8-040',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 600,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },

    // Giratina ex (sv7a-050) — chase card
    {
      cardId: 'sv7a-050',
      marketplace: 'mercari',
      region: 'jp',
      priceCents: 220000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7a-050',
      marketplace: 'yahoo_auctions',
      region: 'jp',
      priceCents: 210000,
      currency: 'JPY',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 2),
    },
    {
      cardId: 'sv7a-050',
      marketplace: 'tcgplayer',
      region: 'en',
      priceCents: 2800,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 0),
    },
    {
      cardId: 'sv7a-050',
      marketplace: 'ebay',
      region: 'en',
      priceCents: 3200,
      currency: 'USD',
      condition: 'near_mint',
      scrapedAt: daysAgo(now, 4),
    },
  ]

  const existingPrices = await db.select().from(prices)
  if (existingPrices.length === 0) {
    for (const price of seedPrices) {
      await db.insert(prices).values(price)
    }
    console.log(`  + ${seedPrices.length} price snapshots seeded`)
  } else {
    console.log(`  = Prices already seeded (${existingPrices.length} records)`)
  }

  // Seed aggregated price stats (current period)
  const periodStart = daysAgo(now, 30)
  const periodEnd = daysAgo(now, 0)
  const seedStats = [
    {
      cardId: 'sv7-010',
      marketplace: 'mercari',
      region: 'jp',
      currency: 'JPY',
      avgPriceCents: 300000,
      minPriceCents: 260000,
      maxPriceCents: 320000,
      medianPriceCents: 290000,
      sampleCount: 4,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7-010',
      marketplace: 'tcgplayer',
      region: 'en',
      currency: 'USD',
      avgPriceCents: 3650,
      minPriceCents: 3500,
      maxPriceCents: 3800,
      medianPriceCents: 3650,
      sampleCount: 2,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7-010',
      marketplace: 'ebay',
      region: 'en',
      currency: 'USD',
      avgPriceCents: 4200,
      minPriceCents: 4200,
      maxPriceCents: 4200,
      medianPriceCents: 4200,
      sampleCount: 1,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7-030',
      marketplace: 'mercari',
      region: 'jp',
      currency: 'JPY',
      avgPriceCents: 155000,
      minPriceCents: 150000,
      maxPriceCents: 160000,
      medianPriceCents: 155000,
      sampleCount: 2,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7-030',
      marketplace: 'tcgplayer',
      region: 'en',
      currency: 'USD',
      avgPriceCents: 1800,
      minPriceCents: 1800,
      maxPriceCents: 1800,
      medianPriceCents: 1800,
      sampleCount: 1,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7-040',
      marketplace: 'mercari',
      region: 'jp',
      currency: 'JPY',
      avgPriceCents: 80000,
      minPriceCents: 75000,
      maxPriceCents: 80000,
      medianPriceCents: 77500,
      sampleCount: 2,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7-040',
      marketplace: 'tcgplayer',
      region: 'en',
      currency: 'USD',
      avgPriceCents: 1200,
      minPriceCents: 1200,
      maxPriceCents: 1200,
      medianPriceCents: 1200,
      sampleCount: 1,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv8-023',
      marketplace: 'mercari',
      region: 'jp',
      currency: 'JPY',
      avgPriceCents: 190000,
      minPriceCents: 170000,
      maxPriceCents: 200000,
      medianPriceCents: 185000,
      sampleCount: 3,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv8-023',
      marketplace: 'tcgplayer',
      region: 'en',
      currency: 'USD',
      avgPriceCents: 2500,
      minPriceCents: 2500,
      maxPriceCents: 2500,
      medianPriceCents: 2500,
      sampleCount: 1,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7a-050',
      marketplace: 'mercari',
      region: 'jp',
      currency: 'JPY',
      avgPriceCents: 215000,
      minPriceCents: 210000,
      maxPriceCents: 220000,
      medianPriceCents: 215000,
      sampleCount: 2,
      periodStart,
      periodEnd,
    },
    {
      cardId: 'sv7a-050',
      marketplace: 'tcgplayer',
      region: 'en',
      currency: 'USD',
      avgPriceCents: 2800,
      minPriceCents: 2800,
      maxPriceCents: 2800,
      medianPriceCents: 2800,
      sampleCount: 1,
      periodStart,
      periodEnd,
    },
  ]

  const existingStats = await db.select().from(priceStats)
  if (existingStats.length === 0) {
    for (const stat of seedStats) {
      await db.insert(priceStats).values(stat)
    }
    console.log(`  + ${seedStats.length} price stats seeded`)
  } else {
    console.log(`  = Price stats already seeded (${existingStats.length} records)`)
  }

  // Seed arbitrage alerts (JP cheaper than EN equivalent in USD)
  // Using approximate rate: 1 USD = 150 JPY
  const seedAlerts = [
    {
      cardId: 'sv7-010',
      jpPriceCents: 280000,
      enPriceCents: 3500,
      jpCurrency: 'JPY',
      enCurrency: 'USD',
      spreadPercent: 87.5,
      jpMarketplace: 'mercari',
      enMarketplace: 'tcgplayer',
      isActive: true,
    },
    {
      cardId: 'sv7-040',
      jpPriceCents: 80000,
      enPriceCents: 1200,
      jpCurrency: 'JPY',
      enCurrency: 'USD',
      spreadPercent: 125.0,
      jpMarketplace: 'mercari',
      enMarketplace: 'tcgplayer',
      isActive: true,
    },
    {
      cardId: 'sv7a-050',
      jpPriceCents: 220000,
      enPriceCents: 2800,
      jpCurrency: 'JPY',
      enCurrency: 'USD',
      spreadPercent: 90.9,
      jpMarketplace: 'mercari',
      enMarketplace: 'tcgplayer',
      isActive: true,
    },
    {
      cardId: 'sv8-023',
      jpPriceCents: 180000,
      enPriceCents: 2500,
      jpCurrency: 'JPY',
      enCurrency: 'USD',
      spreadPercent: 108.3,
      jpMarketplace: 'mercari',
      enMarketplace: 'tcgplayer',
      isActive: true,
    },
    {
      cardId: 'sv7-030',
      jpPriceCents: 150000,
      enPriceCents: 1800,
      jpCurrency: 'JPY',
      enCurrency: 'USD',
      spreadPercent: 80.0,
      jpMarketplace: 'mercari',
      enMarketplace: 'tcgplayer',
      isActive: true,
    },
  ]

  const existingAlerts = await db.select().from(arbitrageAlerts)
  if (existingAlerts.length === 0) {
    for (const alert of seedAlerts) {
      await db.insert(arbitrageAlerts).values(alert)
    }
    console.log(`  + ${seedAlerts.length} arbitrage alerts seeded`)
  } else {
    console.log(`  = Arbitrage alerts already seeded (${existingAlerts.length} records)`)
  }

  console.log('Seeding complete.')
}

function daysAgo(from: Date, days: number): string {
  const d = new Date(from)
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

seed()
