import { eq } from 'drizzle-orm'
import { createDb } from './index.ts'
import { cards, sets } from './schema.ts'

const db = createDb()

// 3 recent JP Pokemon TCG sets with real data
const seedSets = [
  {
    id: 'sv8',
    nameJa: '超電ブレイカー',
    nameEn: 'Super Electric Breaker',
    codeJa: 'SV8',
    codeEn: null,
    seriesJa: 'スカーレット＆バイオレット',
    seriesEn: 'Scarlet & Violet',
    totalCards: 91,
    releaseDateJa: '2025-01-24',
    releaseDateEn: null,
    imageUrl: null,
  },
  {
    id: 'sv7a',
    nameJa: 'パラダイムトリガー',
    nameEn: 'Paradise Dragona',
    codeJa: 'SV7a',
    codeEn: null,
    seriesJa: 'スカーレット＆バイオレット',
    seriesEn: 'Scarlet & Violet',
    totalCards: 75,
    releaseDateJa: '2024-11-08',
    releaseDateEn: null,
    imageUrl: null,
  },
  {
    id: 'sv7',
    nameJa: 'ステラミラクル',
    nameEn: 'Stellar Miracle',
    codeJa: 'SV7',
    codeEn: null,
    seriesJa: 'スカーレット＆バイオレット',
    seriesEn: 'Scarlet & Violet',
    totalCards: 102,
    releaseDateJa: '2024-07-19',
    releaseDateEn: null,
    imageUrl: null,
  },
]

// Sample cards for each set (representative selection)
const seedCards = [
  // SV8 - 超電ブレイカー
  {
    id: 'sv8-001',
    setId: 'sv8',
    numberInSet: '001/091',
    nameJa: 'タマタマ',
    nameEn: 'Exeggcute',
    rarity: 'C',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 50,
    artist: 'Misa Tsutsui',
  },
  {
    id: 'sv8-007',
    setId: 'sv8',
    numberInSet: '007/091',
    nameJa: 'マスカーニャex',
    nameEn: 'Meowscarada ex',
    rarity: 'RR',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 310,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv8-015',
    setId: 'sv8',
    numberInSet: '015/091',
    nameJa: 'ブーバー',
    nameEn: 'Magmar',
    rarity: 'C',
    typeJa: '炎',
    typeEn: 'Fire',
    hp: 80,
    artist: 'Sanosuke Sakuma',
  },
  {
    id: 'sv8-023',
    setId: 'sv8',
    numberInSet: '023/091',
    nameJa: 'ミライドンex',
    nameEn: 'Miraidon ex',
    rarity: 'RR',
    typeJa: '雷',
    typeEn: 'Lightning',
    hp: 220,
    artist: '5ban Graphics',
  },
  {
    id: 'sv8-030',
    setId: 'sv8',
    numberInSet: '030/091',
    nameJa: 'テツノカシラex',
    nameEn: 'Iron Crown ex',
    rarity: 'RR',
    typeJa: '超',
    typeEn: 'Psychic',
    hp: 220,
    artist: 'PLANETA Igarashi',
  },
  {
    id: 'sv8-040',
    setId: 'sv8',
    numberInSet: '040/091',
    nameJa: 'ガブリアスex',
    nameEn: 'Garchomp ex',
    rarity: 'RR',
    typeJa: '闘',
    typeEn: 'Fighting',
    hp: 330,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv8-050',
    setId: 'sv8',
    numberInSet: '050/091',
    nameJa: 'サザンドラex',
    nameEn: 'Hydreigon ex',
    rarity: 'RR',
    typeJa: '悪',
    typeEn: 'Darkness',
    hp: 320,
    artist: '5ban Graphics',
  },
  {
    id: 'sv8-060',
    setId: 'sv8',
    numberInSet: '060/091',
    nameJa: 'ジュラルドンex',
    nameEn: 'Duraludon ex',
    rarity: 'RR',
    typeJa: '鋼',
    typeEn: 'Metal',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv8-070',
    setId: 'sv8',
    numberInSet: '070/091',
    nameJa: 'カビゴン',
    nameEn: 'Snorlax',
    rarity: 'U',
    typeJa: '無',
    typeEn: 'Colorless',
    hp: 150,
    artist: 'Kouki Saitou',
  },
  {
    id: 'sv8-080',
    setId: 'sv8',
    numberInSet: '080/091',
    nameJa: 'ボスの指令',
    nameEn: "Boss's Orders",
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: 'GOSSAN',
  },

  // SV7a - パラダイムトリガー
  {
    id: 'sv7a-001',
    setId: 'sv7a',
    numberInSet: '001/075',
    nameJa: 'キャタピー',
    nameEn: 'Caterpie',
    rarity: 'C',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 50,
    artist: 'Saya Tsuruta',
  },
  {
    id: 'sv7a-010',
    setId: 'sv7a',
    numberInSet: '010/075',
    nameJa: 'ウルガモスex',
    nameEn: 'Volcarona ex',
    rarity: 'RR',
    typeJa: '炎',
    typeEn: 'Fire',
    hp: 270,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7a-020',
    setId: 'sv7a',
    numberInSet: '020/075',
    nameJa: 'パルキアex',
    nameEn: 'Palkia ex',
    rarity: 'RR',
    typeJa: '水',
    typeEn: 'Water',
    hp: 280,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv7a-030',
    setId: 'sv7a',
    numberInSet: '030/075',
    nameJa: 'ディアルガex',
    nameEn: 'Dialga ex',
    rarity: 'RR',
    typeJa: '鋼',
    typeEn: 'Metal',
    hp: 280,
    artist: 'PLANETA Igarashi',
  },
  {
    id: 'sv7a-040',
    setId: 'sv7a',
    numberInSet: '040/075',
    nameJa: 'アルセウスex',
    nameEn: 'Arceus ex',
    rarity: 'RR',
    typeJa: '無',
    typeEn: 'Colorless',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7a-050',
    setId: 'sv7a',
    numberInSet: '050/075',
    nameJa: 'ギラティナex',
    nameEn: 'Giratina ex',
    rarity: 'RR',
    typeJa: '超',
    typeEn: 'Psychic',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7a-055',
    setId: 'sv7a',
    numberInSet: '055/075',
    nameJa: 'シロナの覇気',
    nameEn: "Cynthia's Ambition",
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: 'Yusuke Kozaki',
  },
  {
    id: 'sv7a-060',
    setId: 'sv7a',
    numberInSet: '060/075',
    nameJa: 'ダブルターボエネルギー',
    nameEn: 'Double Turbo Energy',
    rarity: 'U',
    typeJa: 'エネルギー',
    typeEn: 'Energy',
    hp: null,
    artist: null,
  },

  // SV7 - ステラミラクル
  {
    id: 'sv7-001',
    setId: 'sv7',
    numberInSet: '001/102',
    nameJa: 'フシギダネ',
    nameEn: 'Bulbasaur',
    rarity: 'C',
    typeJa: '草',
    typeEn: 'Grass',
    hp: 70,
    artist: 'Narumi Sato',
  },
  {
    id: 'sv7-010',
    setId: 'sv7',
    numberInSet: '010/102',
    nameJa: 'リザードンex',
    nameEn: 'Charizard ex',
    rarity: 'RR',
    typeJa: '炎',
    typeEn: 'Fire',
    hp: 330,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv7-020',
    setId: 'sv7',
    numberInSet: '020/102',
    nameJa: 'カメックスex',
    nameEn: 'Blastoise ex',
    rarity: 'RR',
    typeJa: '水',
    typeEn: 'Water',
    hp: 330,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-030',
    setId: 'sv7',
    numberInSet: '030/102',
    nameJa: 'ピカチュウex',
    nameEn: 'Pikachu ex',
    rarity: 'RR',
    typeJa: '雷',
    typeEn: 'Lightning',
    hp: 200,
    artist: 'PLANETA Mochizuki',
  },
  {
    id: 'sv7-040',
    setId: 'sv7',
    numberInSet: '040/102',
    nameJa: 'ミュウツーex',
    nameEn: 'Mewtwo ex',
    rarity: 'RR',
    typeJa: '超',
    typeEn: 'Psychic',
    hp: 280,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-050',
    setId: 'sv7',
    numberInSet: '050/102',
    nameJa: 'ルカリオex',
    nameEn: 'Lucario ex',
    rarity: 'RR',
    typeJa: '闘',
    typeEn: 'Fighting',
    hp: 270,
    artist: 'PLANETA Igarashi',
  },
  {
    id: 'sv7-060',
    setId: 'sv7',
    numberInSet: '060/102',
    nameJa: 'ゲンガーex',
    nameEn: 'Gengar ex',
    rarity: 'RR',
    typeJa: '悪',
    typeEn: 'Darkness',
    hp: 270,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-070',
    setId: 'sv7',
    numberInSet: '070/102',
    nameJa: 'テラパゴスex',
    nameEn: 'Terapagos ex',
    rarity: 'RR',
    typeJa: '無',
    typeEn: 'Colorless',
    hp: 230,
    artist: '5ban Graphics',
  },
  {
    id: 'sv7-080',
    setId: 'sv7',
    numberInSet: '080/102',
    nameJa: 'ナンジャモ',
    nameEn: 'Iono',
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: 'take',
  },
  {
    id: 'sv7-090',
    setId: 'sv7',
    numberInSet: '090/102',
    nameJa: 'ネストボール',
    nameEn: 'Nest Ball',
    rarity: 'U',
    typeJa: 'トレーナーズ',
    typeEn: 'Trainer',
    hp: null,
    artist: null,
  },
]

async function seed() {
  console.log('Seeding database...')

  for (const set of seedSets) {
    const existing = await db.select().from(sets).where(eq(sets.id, set.id))
    if (existing.length === 0) {
      await db.insert(sets).values(set)
      console.log(`  + Set: ${set.nameJa} (${set.codeJa})`)
    } else {
      console.log(`  = Set already exists: ${set.nameJa}`)
    }
  }

  for (const card of seedCards) {
    const existing = await db.select().from(cards).where(eq(cards.id, card.id))
    if (existing.length === 0) {
      await db.insert(cards).values(card)
      console.log(`  + Card: ${card.nameJa} / ${card.nameEn}`)
    } else {
      console.log(`  = Card already exists: ${card.nameJa}`)
    }
  }

  console.log('Seeding complete.')
}

seed()
